source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "sequel"
gem "sqlite3"
gem "rufus-scheduler"
gem "faraday"
gem "faraday-cookie_jar"
gem "dotenv"
gem "tzinfo" 
gem "rackup" 
gem "puma" 
